import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import NavBar from '@/components/NavBar/NavBar';
import './globals.css';
import Footer from '@/components/Footer/Footer';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Maria's Moments",
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body className="h-screen bg-neutral-900 text-white">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
